### PR TITLE
Fix crash in Auth when running unit tests

### PR DESCRIPTION
**Pull request by aashishpatil-g**
Fixes the crash in Auth when running Unit Tests. This is because the Auth SDK expects an API key in 11.x SDK. The tests were not supplying a dummy key.

### CODE REVIEW

**Review by paulb777 — COMMENTED** [review]
Please fix formatting and address this TODO - https://github.com/firebase/data-connect-ios-sdk/blob/main/.github/workflows/spm.yml#L45

**Comment by paulb777** [comment]
May also need to make separate targets in Package.swift for unit and integration tests

**Review by paulb777 — APPROVED** [review]
Assuming the tests run locally, OK to merge here and address CI issues separately. either way.

**Comment by aashishpatil-g** [comment]
Yes, Unit tests are succeeding locally. I'll start a separate PR to fix the TODO and create a separate Unit Test target

**Pull request merged**
